// <auto-generated />
using System;
using BarberShopAPI.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarberShopAPI.Server.Migrations
{
    [DbContext(typeof(BarberShopContext))]
    [Migration("20250923135113_AddUsedPasswordResetTokens")]
    partial class AddUsedPasswordResetTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarberShopAPI.Server.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("HasCustomPassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("admins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@thebarberbook.com",
                            HasCustomPassword = false,
                            IsActive = true,
                            Name = "Barber Admin",
                            PasswordHash = "$2a$11$benDf35qRWXNw0osak1bT.l0YJzO8HvMF97sPDan1awa2M6ZrhYx6",
                            TenantId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "amazedave15@gmail.com",
                            HasCustomPassword = false,
                            IsActive = true,
                            Name = "Elite Cuts Admin",
                            PasswordHash = "$2a$11$1f2fGZFonZYlqMVjU4JDaOwE5ieYIiUnrq.hU3LNlmMP9l4qOL2EG",
                            TenantId = 2,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("BarberShopAPI.Server.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Confirmed");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TenantId");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("BarberShopAPI.Server.Models.BarberShop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AdminPasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BusinessAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BusinessHours")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BusinessPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Arial, sans-serif")
                        .HasColumnName("fontfamily");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#000000")
                        .HasColumnName("secondarycolor");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ThemeColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#D4AF37")
                        .HasColumnName("themecolor");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("barbershops", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminEmail = "CleanCuts@thebarberbook.com",
                            AdminPasswordHash = "$2a$11$lAJCNG2qgXjW11SmKtSczendtw7M/RcHTq8chwceU9.GNX00I6sTi",
                            BusinessAddress = "123 Main Street",
                            BusinessHours = "Mon-Fri: 9AM-6PM, Sat: 9AM-4PM, Sun: Closed",
                            BusinessPhone = "(123) 456-7890",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FontFamily = "Arial, sans-serif",
                            IsActive = true,
                            Name = "Clean Cuts",
                            SecondaryColor = "#000000",
                            Subdomain = "default",
                            ThemeColor = "#D4AF37",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AdminEmail = "amazedave15@gmail.com",
                            AdminPasswordHash = "$2a$11$EdP4jFzY7y39s8jwINve6OzW31gGSCSQw6PhQHB5qcmPLU4/SespS",
                            BusinessAddress = "456 Oak Street",
                            BusinessHours = "Mon-Fri: 9AM-7PM, Sat: 9AM-5PM, Sun: Closed",
                            BusinessPhone = "(555) 123-4567",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FontFamily = "Arial, sans-serif",
                            IsActive = true,
                            Name = "Elite Cuts",
                            SecondaryColor = "#000000",
                            Subdomain = "elite",
                            ThemeColor = "#D4AF37",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BarberShopAPI.Server.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("services", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Professional haircut with styling",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Classic Haircut",
                            Price = 30.00m,
                            TenantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Creative hair design and styling",
                            DurationMinutes = 10,
                            IsActive = true,
                            Name = "Design",
                            Price = 5.00m,
                            TenantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Professional beard trimming and shaping",
                            DurationMinutes = 10,
                            IsActive = true,
                            Name = "Beard Trimming",
                            Price = 5.00m,
                            TenantId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Eyebrow trimming and shaping",
                            DurationMinutes = 5,
                            IsActive = true,
                            Name = "Eyebrows",
                            Price = 5.00m,
                            TenantId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Luxury haircut with premium styling",
                            DurationMinutes = 75,
                            IsActive = true,
                            Name = "Premium Haircut",
                            Price = 45.00m,
                            TenantId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Professional beard sculpting and design",
                            DurationMinutes = 20,
                            IsActive = true,
                            Name = "Beard Sculpting",
                            Price = 15.00m,
                            TenantId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Professional hair styling and finishing",
                            DurationMinutes = 15,
                            IsActive = true,
                            Name = "Hair Styling",
                            Price = 10.00m,
                            TenantId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Precision eyebrow design and shaping",
                            DurationMinutes = 10,
                            IsActive = true,
                            Name = "Eyebrow Design",
                            Price = 8.00m,
                            TenantId = 2
                        });
                });

            modelBuilder.Entity("BarberShopAPI.Server.Models.Admin", b =>
                {
                    b.HasOne("BarberShopAPI.Server.Models.BarberShop", "Tenant")
                        .WithMany("Admins")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BarberShopAPI.Server.Models.Appointment", b =>
                {
                    b.HasOne("BarberShopAPI.Server.Models.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberShopAPI.Server.Models.BarberShop", "Tenant")
                        .WithMany("Appointments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BarberShopAPI.Server.Models.Service", b =>
                {
                    b.HasOne("BarberShopAPI.Server.Models.BarberShop", "Tenant")
                        .WithMany("Services")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BarberShopAPI.Server.Models.BarberShop", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Appointments");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("BarberShopAPI.Server.Models.Service", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
